export const indianCities = [
  "Agra",
  "Ahmedabad",
  "Ahmednagar",
  "Ajmer",
  "Akola",
  "Aligarh",
  "Alwar",
  "Amravati",
  "Amritsar",
  "Anantapuram",
  "Asansol",
  "Aurangabad",
  "Avadi",
  "Bally",
  "Bangalore",
  "Bardhaman",
  "Bareilly",
  "Bathinda",
  "Bellary",
  "Belgaum",
  "Bhavnagar",
  "Bhilai",
  "Bhilwara",
  "Bhiwandi",
  "Bhopal",
  "Bhubaneswar",
  "Bihar Sharif",
  "Bikaner",
  "Bilaspur",
  "Bokaro Steel City",
  "Chandigarh",
  "Chandrapur",
  "Chennai",
  "Coimbatore",
  "Cuttack",
  "Darbhanga",
  "Dehradun",
  "Delhi",
  "Dewas",
  "Dhule",
  "Dindigul",
  "Durgapur",
  "Eluru",
  "Erode",
  "Faridabad",
  "Firozabad",
  "Gandhinagar",
  "Gaya",
  "Ghaziabad",
  "Gorakhpur",
  "Gulbarga",
  "Guna",
  "Guntur",
  "Gurgaon",
  "Guwahati",
  "Gwalior",
  "Haridwar",
  "Hassan",
  "Howrah",
  "Hubli-Dharwad",
  "Hyderabad",
  "Ichalkaranji",
  "Imphal",
  "Indore",
  "Itanagar",
  "Jabalpur",
  "Jaipur",
  "Jalandhar",
  "Jalna",
  "Jamnagar",
  "Jammu",
  "Jamshedpur",
  "Jhansi",
  "Jind",
  "Jodhpur",
  "Junagadh",
  "Kadapa",
  "Kakinada",
  "Kalyan-Dombivli",
  "Kamarhati",
  "Kanpur",
  "Karnal",
  "Katihar",
  "Khammam",
  "Kochi",
  "Kohima",
  "Kolhapur",
  "Kolkata",
  "Kollam",
  "Korba",
  "Kota",
  "Kulti",
  "Kurnool",
  "Latur",
  "Lucknow",
  "Ludhiana",
  "Madurai",
  "Malegaon",
  "Mangalore",
  "Mathura",
  "Meerut",
  "Moradabad",
  "Muzaffarnagar",
  "Muzaffarpur",
  "Mysore",
  "Nagercoil",
  "Nagpur",
  "Naihati",
  "Nanded",
  "Nashik",
  "Navi Mumbai",
  "Nellore",
  "Nizamabad",
  "Noida",
  "Ongole",
  "Ozhukarai",
  "Panihati",
  "Panipat",
  "Parbhani",
  "Patna",
  "Pimpri-Chinchwad",
  "Pondicherry",
  "Pune",
  "Purnia",
  "Raipur",
  "Rajahmundry",
  "Rajkot",
  "Ramagundam",
  "Rampur",
  "Ranchi",
  "Raniganj",
  "Rishikesh",
  "Rohtak",
  "Rourkela",
  "Saharanpur",
  "Sagar",
  "Salem",
  "Sambalpur",
  "Sangli-Miraj & Kupwad",
  "Satara",
  "Secunderabad",
  "Shahjahanpur",
  "Shillong",
  "Shimla",
  "Shivamogga",
  "Silchar",
  "Siliguri",
  "Solapur",
  "Sonipat",
  "Srinagar",
  "Surat",
  "Thane",
  "Thrissur",
  "Tinsukia",
  "Tiruchirappalli",
  "Tirunelveli",
  "Tumkur",
  "Udaipur",
  "Ujjain",
  "Ulhasnagar",
  "Vadodara",
  "Varanasi",
  "Vasai-Virar",
  "Vijayawada",
  "Visakhapatnam",
  "Warangal",
];

export const indianStatesAndUTs = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];

export const validImageFormats = [
  "apng",
  "avif",
  "gif",
  "jpg",
  "jpeg",
  "png",
  "svg",
  "webp",
  "ico",
];

export const emailValidationRegex =
  /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;

export async function turnHttpUrlToBlob(httpUrl) {
  try {
    const imageFetchResponse = await fetch(httpUrl, {
      credentials: "include",
      headers: {
        "File-Name": image,
      },
    });
    if (!imageFetchResponse.ok)
      throw new Error("Failed to fetch image from the url.");
    const imageBlob = await imageFetchResponse.blob();
    return URL.createObjectURL(imageBlob);
  } catch (error) {
    throw new Error(error.message);
  }
}
